server:
  port: 8090

spring:
  application:
    name: mcp‑tool‑server
  config:
    import: optional:nacos
  ai:
    mcp:
      server:
        enabled: true
        name: mcp-tool-server
        version: 1.0.0
        protocol: STREAMABLE
        streamable-http:
          mcp-endpoint: /mcp
          keep-alive-interval: 30s
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: public
        register-enabled: false # 关闭自动注册
      config:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: public
        import-check:
          enabled: false

# 打开自动配置报告，排查404时开启
debug: true

# 天气API配置
weather:
  api-url: https://wttr.in/%s?format=j1&lang=zh

# RocketMQ Proxy
rocketmq:
  proxy-endpoint: 127.0.0.1:8081

# Qdrant
qdrant:
  rest-url: http://127.0.0.1:6333
  collection-name: doc_rag_collection
  embedding-dimension: 1024

dashscope:
  api-key: sk-ws-H.ERYDLPY.L8gU.MEQCIGX03YaCpLs4ka5EvbyrFBBWxCrD5Niw9gZ2oxhvgkL9AiB6YolIS54wSPsbXYZ-_W55AXABpenBx0gqVj3SoFk8YA
  embedding-model: text-embedding-v3
  base-url: https://dashscope.aliyuncs.com/compatible-mode/v1

embedding:
  chunk:
    size: 500
    overlap: 100